### ISSUE TITLE
회원 관련 상수 테이블(권한, 등급) 정의

### ISSUE THREAD

**Issue by JoonheeJeong** [JoonheeJeong/fc5-toy3-board#1]
### To-do
- [x] 디비 스키마 정의
- [x] 상수 데이터 정의
- [x] 모델 정의
- [x] 레포지토리 구현 및 테스트
  - [x] application.yml 설정
